# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160507_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='src',
            field=models.URLField(default='none', max_length=1000),
        ),
    ]
